#!/bin/bash

echo "=========================================================="
echo " Skrypt ze zminnymi  env              "         
echo "========================================================="
echo ""
echo "jestes zalogowany jak $USER"
echo ""
echo "Twoja lokalizacja to: $PWD"
echo ""
echo "twój domowy katalog to: $HOME"
echo  ""
echo "Twoja mienna PATH wygląda tak: $PATH"
echo ""
echo " System: $DESKTOP_SESSION" 
echo ""
echo "======================================================== "